<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wo_timer_label2</name>
   <tag></tag>
   <elementGuidId>6523c2ce-7b4f-46bf-9971-6a09d87673b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table/tbody/tr[7]/td[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
