<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_contentFrame</name>
   <tag></tag>
   <elementGuidId>ae42282a-b633-437c-b617-fecd3bcfaf2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'contentFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#contentFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;contentFrame&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4bd04d66-366a-4d4f-9129-7dbeab079025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ph-wo-min-height-475px</value>
      <webElementGuid>59149389-c05b-4cbb-bcdf-f500060d694d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contentFrame</value>
      <webElementGuid>b7bbd18c-4b01-4be9-8c60-94c0b2bcebd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contentFrame</value>
      <webElementGuid>b51cdbf0-dc45-4e2c-931e-250bdcb2f5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>262c33e6-0868-471d-ae73-1572cf92702c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/phworkoutput/WorkOutputSettingSummary.htm?menuItemId=294&amp;menuClick=true</value>
      <webElementGuid>586e0487-38be-4b3f-9dc9-9fe026bb253e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-191f93781284f0fc21281f07e8530b45</value>
      <webElementGuid>75c4098d-101a-4ddc-afcf-35daef46c8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'contentFrame']</value>
      <webElementGuid>d20c6337-1236-48c4-93e3-481eded0b4b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'contentFrame']</value>
      <webElementGuid>18ef1d59-6232-461d-a392-aee639dfdba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'contentFrame' and @name = 'contentFrame' and @src = '/phworkoutput/WorkOutputSettingSummary.htm?menuItemId=294&amp;menuClick=true']</value>
      <webElementGuid>00dfcc31-6900-4f50-817b-ca0ed5781c85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
