<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Would you like to terminate the other_21bc89</name>
   <tag></tag>
   <elementGuidId>c66abb08-b697-4d01-9422-00324a9daddc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#distroysession</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='distroysession']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Yes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f82c091a-d299-4cb7-bbba-24df3ff510fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>534cf64f-85b6-4d96-8f10-922443c17148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>distroysession</value>
      <webElementGuid>0e54aaa9-d9bf-4f72-bb6e-3ea28830c3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-login</value>
      <webElementGuid>c7d46f08-a70e-41b8-a6c4-9261f5ca8a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>c80a9949-4c6d-4b71-b229-0ff1da3ed2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;distroysession&quot;)</value>
      <webElementGuid>d900c326-68ca-434c-97f7-e006cba54d5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='distroysession']</value>
      <webElementGuid>8066e019-90c4-41c6-ac58-70dfe83a4172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loadContent']/div/div/div[4]/div/div/input</value>
      <webElementGuid>5ef72b74-bbfb-444b-a411-62de370cacd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>a29b97b5-0ef0-4353-ba79-e28be2e44d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'distroysession']</value>
      <webElementGuid>c3c5fbac-64a8-4b7b-8ed6-819fa45995db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
