<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_dipankar_process (1)</name>
   <tag></tag>
   <elementGuidId>7ce84a55-a433-43f0-8398-be5246fd0e09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='CommonDataTableId']/tbody/tr/td/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ph-wo-word-break-break-all</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;#dipankar_process&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7e26d912-5db1-4ffa-b53a-bb4e1414167e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ph-wo-word-break-break-all</value>
      <webElementGuid>2bebbe15-26ef-4dac-85a7-8973e4a22cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>#dipankar_process</value>
      <webElementGuid>04d2d326-7064-40ea-ad0c-93af07c9c935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CommonDataTableId&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text sorting_1&quot;]/div[@class=&quot;ph-wo-word-break-break-all&quot;]</value>
      <webElementGuid>e4a74241-2a62-4f6c-b455-5f3a037bab57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ProHance Work Output/Page_ProHance Work Output/iframe_Work Output Settings_contentFrame_1</value>
      <webElementGuid>a8c2193b-746f-4a4a-a749-4e67c5313c04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='CommonDataTableId']/tbody/tr/td/div</value>
      <webElementGuid>636dc9df-9d2f-4a0b-89e3-2ced74215f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::div[1]</value>
      <webElementGuid>d70aab7d-57df-4f90-bfec-eacc24faf1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#User Groups'])[1]/following::div[1]</value>
      <webElementGuid>f2f4a3af-3e36-4b6e-ab02-473a492109b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WO Scoredcard 2.0'])[1]/preceding::div[1]</value>
      <webElementGuid>35a9571d-3da9-4bcb-87c0-ff8f21a22b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::div[2]</value>
      <webElementGuid>c4624eda-3851-4b6b-8be5-262f4be1607b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='#dipankar_process']/parent::*</value>
      <webElementGuid>fac73336-8417-4fa9-82b6-bc71f8591abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td/div</value>
      <webElementGuid>98b33612-3508-45b1-b4f2-4f746894b2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '#dipankar_process' or . = '#dipankar_process')]</value>
      <webElementGuid>e6fc562e-5151-4aca-ae46-799e6ca02d7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
