<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Work Output Settings_contentFrame_1</name>
   <tag></tag>
   <elementGuidId>44021814-4d4c-4c7f-b375-ecb0d53be460</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='contentFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#contentFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;contentFrame&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>810e6540-689b-4168-afc2-5ea163ee3765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ph-wo-min-height-475px</value>
      <webElementGuid>1e2032b1-b006-438b-abdb-faf8a519f2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contentFrame</value>
      <webElementGuid>9439321d-4bae-40ba-9dd7-8c831e572f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contentFrame</value>
      <webElementGuid>8059b2d9-e892-4b71-8bd8-9298683904e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dbb9c7d7-0817-4254-ab73-f0fdbb04a5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/phworkoutput/WorkOutputCategorySummary.htm?menuItemId=302&amp;menuClick=true</value>
      <webElementGuid>9f346d47-aa60-4f17-a4e0-8abfe67739c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentFrame&quot;)</value>
      <webElementGuid>fe8cca97-b31f-4e0f-b3bb-d1739b51adff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='contentFrame']</value>
      <webElementGuid>96db3489-00f5-4e0f-add4-65bbcdd81476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyContent']/div[3]/div/iframe</value>
      <webElementGuid>73252eb8-eb82-493a-a448-ef60c130ea68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>1c15c415-aaba-44e1-89a8-51ab19aa5f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'contentFrame' and @name = 'contentFrame' and @src = '/phworkoutput/WorkOutputCategorySummary.htm?menuItemId=302&amp;menuClick=true']</value>
      <webElementGuid>b0a59c95-32ad-4990-972e-0819cb5842da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
