<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Work Type Category</name>
   <tag></tag>
   <elementGuidId>ee2b2ad7-ef20-4c27-a714-475fd36c1ff7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='level2_291']/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#level2_291 > li:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Work Type Category&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5c066dc9-dc0d-4b36-977e-64b5b7ea7fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnMenuClick</value>
      <webElementGuid>f6416c20-037f-40dd-8ca7-4992f205bf6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menuid</name>
      <type>Main</type>
      <value>302</value>
      <webElementGuid>b07b011f-ad49-4dda-b583-0ab6630eb501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-path</name>
      <type>Main</type>
      <value>/phworkoutput/WorkOutputCategorySummary.htm?menuItemId=302&amp;menuClick=true</value>
      <webElementGuid>c105d3a1-9693-4800-9bd4-3fd8e11a1cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isajaxsidemenu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f3116d62-22fb-42ce-a673-a74672bccce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Work Type Category</value>
      <webElementGuid>bef5c2de-6e27-41a0-b677-7f200e1553bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;level2_291&quot;)/li[@class=&quot;&quot;]</value>
      <webElementGuid>384ba1f3-6b12-4299-be79-d02d1eb071d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='level2_291']/li[2]</value>
      <webElementGuid>391caf53-54cc-49cd-bb0f-0ac9b8f45ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Output Parameter'])[1]/following::li[1]</value>
      <webElementGuid>f7c3bd77-392c-4a30-91a5-03dda42007c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration'])[1]/following::li[2]</value>
      <webElementGuid>1c61666c-21d4-48ef-82cd-94de73a1e939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Type Attributes'])[1]/preceding::li[1]</value>
      <webElementGuid>3204a8e5-adde-4dca-9767-d89fffbfafad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Type Definition'])[1]/preceding::li[2]</value>
      <webElementGuid>4584af4b-c8f9-4aec-9539-0cd39e392d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Work Type Category']/parent::*</value>
      <webElementGuid>9032c3b6-e571-4ea0-9863-a612af489f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[2]</value>
      <webElementGuid>de0f3b19-1dff-45a8-b1d1-b9de4ed8bf86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Work Type Category' or . = 'Work Type Category')]</value>
      <webElementGuid>4967ada6-fb6d-45ed-85cb-6e848c0cbbd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
