<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Work Type_ph-dash-cursor-pointer</name>
   <tag></tag>
   <elementGuidId>7f04408b-236b-4cbc-b51d-5fae2ab16e16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.ph-dash-cursor-pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Specific Work Type&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>24e0ad57-0bd3-4a23-84cd-0c59c030a244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/phworkoutput/images/popup_icon.gif</value>
      <webElementGuid>5a4b85c1-6c37-4f02-85ac-c8bae2b8fe77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Specific Work Type</value>
      <webElementGuid>ee42b159-4e7c-4150-9084-25da6d3c02fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ph-dash-cursor-pointer</value>
      <webElementGuid>fc96fb63-fb1d-4aef-9f05-686a906355f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;worktypePopupIcon&quot;)/img[@class=&quot;ph-dash-cursor-pointer&quot;]</value>
      <webElementGuid>3e1d7270-76b4-4265-bf4c-83c052c38a1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='worktypePopupIcon']/img</value>
      <webElementGuid>3a64f7d7-bbb1-44ef-8b2b-b0ca51a17929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Specific Work Type']</value>
      <webElementGuid>4b518e30-1ff9-4b16-94bf-b832e1a6c7b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/span/span/img</value>
      <webElementGuid>ade9d961-24c7-480f-ab98-258158c64a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/phworkoutput/images/popup_icon.gif' and @title = 'Specific Work Type']</value>
      <webElementGuid>1202608a-4620-400f-9749-18478820f235</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
