<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Output Trend</name>
   <tag></tag>
   <elementGuidId>85be2462-1745-4c5e-8d1e-549f6045495e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='widget-title-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#widget-title-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#widget-title-3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f942d7d5-eacb-44a2-92b0-9b3c26011821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>widget-title-3</value>
      <webElementGuid>5da6cfc8-8480-41c0-b31e-62676b0ebc3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Business Rating [Avg. AHT] For Client Team (Windows), By Day </value>
      <webElementGuid>e0e21954-a389-43b5-8a64-38bc38d1ca85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Output Trend</value>
      <webElementGuid>08f620af-9b18-49f7-9bfb-15f14624f8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;widget-title-3&quot;)</value>
      <webElementGuid>c7d29d44-3dbe-4bda-9f04-0667ea80ef9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='widget-title-3']</value>
      <webElementGuid>a6fc5705-f532-4eab-9645-3ca8a5cf5fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='wo-container_3']/div/div/div/span</value>
      <webElementGuid>ea090537-800a-41e2-943c-b884889d4050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vignesh B Jawahar'])[1]/following::span[1]</value>
      <webElementGuid>970d40bf-5c36-4a5f-bd6f-5c6efae8ff29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dipankar MAC'])[1]/following::span[1]</value>
      <webElementGuid>e52b9381-a319-43b9-b80e-6b8b38ea8613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=': Business Rating [Avg. AHT] For...'])[1]/preceding::span[1]</value>
      <webElementGuid>f44a67ac-7b11-4467-bdaf-b28c056f1537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to remove this widget?'])[2]/preceding::span[6]</value>
      <webElementGuid>35b3d213-55c4-427c-a671-2d40eae8d96e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/span</value>
      <webElementGuid>a1af127a-a665-47de-bc35-270b5fbd9721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'widget-title-3' and @title = 'Business Rating [Avg. AHT] For Client Team (Windows), By Day ' and (text() = 'Output Trend' or . = 'Output Trend')]</value>
      <webElementGuid>2c0de4ed-2016-4d12-af3c-5a79b3652679</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
