<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add New Widget</name>
   <tag></tag>
   <elementGuidId>1d5011b8-d009-41c3-9dec-6cd45503fce4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='show-content-menu-main']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#show-content-menu-main</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#show-content-menu-main</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a56754ff-3b23-421f-aad7-56226631cf81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add-new-name</value>
      <webElementGuid>dafab293-83ef-4530-9cc3-70dcafc1b70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show-content-menu-main</value>
      <webElementGuid>2c8b3c76-ff46-4f76-8046-131f0d3114c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add New Widget</value>
      <webElementGuid>bed041a5-921d-449a-af27-6a7bf5d6e640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show-content-menu-main&quot;)</value>
      <webElementGuid>3c9ff2fa-b2eb-458d-a4d3-9323a60eb885</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='show-content-menu-main']</value>
      <webElementGuid>6bde185c-235a-41cd-b4ee-40b7dda2c7c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show-content-menu']/div/span</value>
      <webElementGuid>8274db4b-9528-4dcc-ae6b-7daa9520d918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Output Data Management.'])[1]/following::span[1]</value>
      <webElementGuid>2f17cdd2-0da4-4af8-8cfa-f79b5c47e856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Import'])[2]/following::span[1]</value>
      <webElementGuid>aa93467b-229f-4116-9a20-680455eb203b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/div/div/div/div/span</value>
      <webElementGuid>be7e63b4-8bdd-4171-b3ce-3486b5a11e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'show-content-menu-main' and (text() = ' Add New Widget' or . = ' Add New Widget')]</value>
      <webElementGuid>8a6d4495-f7e5-4382-bab1-a473b2be53a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
