<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Business Rating Avg. AHT For_filter_3</name>
   <tag></tag>
   <elementGuidId>833cc152-02ce-4728-82b3-667bd7d54efa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;widget-title-label&quot;]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#filter_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#filter_3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ef0a6f95-9576-4d2e-bc37-ca07e7624932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Report Filter</value>
      <webElementGuid>2b089cd1-2887-4e47-96ec-845542a940c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>widget-tools tool-filter</value>
      <webElementGuid>b8177021-0311-4b41-8367-674c7091b8bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter_3</value>
      <webElementGuid>38fcaea5-4d94-4722-9aa4-f50674334a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnGetFilter</value>
      <webElementGuid>883c13aa-851a-48e7-9f8c-ce6a211e0f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param1</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>785a62ed-55ea-4f5b-876d-344a98e860d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param2</name>
      <type>Main</type>
      <value>WO_TrendReport</value>
      <webElementGuid>f5033c87-b1fd-4760-b595-0679885946d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param3</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5f2dbc40-8863-4b5a-82d9-c23e89d4a6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param4</name>
      <type>Main</type>
      <value>NWODashboardTrendReport</value>
      <webElementGuid>d2d2d458-1eec-4447-9483-f802d9a4b9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter_3&quot;)</value>
      <webElementGuid>ab1e3078-32f9-48b5-85e0-386cea44d1ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='filter_3']</value>
      <webElementGuid>82f62560-dd82-4537-b882-36e63027e30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='wo-container_3']/div/div/div[2]/span[3]</value>
      <webElementGuid>adaf62ef-e960-4fd3-90b4-66ff44e0abff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div[2]/span[3]</value>
      <webElementGuid>db203d23-2146-42a0-835b-73bdc47245ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Report Filter' and @id = 'filter_3']</value>
      <webElementGuid>6e5880bb-be17-4c34-9e8a-8938f271894f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
