<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Work Type</name>
   <tag></tag>
   <elementGuidId>c4f6af6f-da46-4a46-8f45-1ccde5f1d157</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CommonDataTableWorkTypeId_wrapper']/div[4]/div/div/table/thead/tr/th[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.text.nowrap.sorting.sorting_asc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Work Type: activate to sort column descending&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>b6f843cd-f887-401b-934e-337165081089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text nowrap sorting sorting_asc</value>
      <webElementGuid>75d1babe-077c-4eef-affe-8e400550c70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e3f5a6f3-5c55-4f17-9fd9-0f96fcac1326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>CommonDataTableWorkTypeId</value>
      <webElementGuid>0bb6d5a1-f504-45a1-93f7-574fdc341484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>af533d9a-366c-4a79-a240-20dfa8ff9997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7eff8a2b-9fad-4bfb-8635-937a3a7d7326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-sort</name>
      <type>Main</type>
      <value>ascending</value>
      <webElementGuid>76296bb4-a42c-4939-bf63-7bd8327b3073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Work Type: activate to sort column descending</value>
      <webElementGuid>5fc8646f-d6fc-4f05-a0c0-84ca19d64637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Work Type</value>
      <webElementGuid>c298e83e-e0c2-4152-be0b-cbccce146875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CommonDataTableWorkTypeId_wrapper&quot;)/div[@class=&quot;dataTables_scroll&quot;]/div[@class=&quot;dataTables_scrollHead&quot;]/div[@class=&quot;dataTables_scrollHeadInner&quot;]/table[@class=&quot;table no-footer dataTable&quot;]/thead[1]/tr[1]/th[@class=&quot;text nowrap sorting sorting_asc&quot;]</value>
      <webElementGuid>2a74cae5-50f3-4572-970e-e0319b5e8560</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CommonDataTableWorkTypeId_wrapper']/div[4]/div/div/table/thead/tr/th[2]</value>
      <webElementGuid>9d1d2efc-74e7-4744-b4db-600b5fd5a84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::th[2]</value>
      <webElementGuid>f5574933-e1ad-4deb-93cb-53bff7af2fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Type'])[3]/preceding::th[2]</value>
      <webElementGuid>d068b83d-1322-4e6f-b6b4-bd7a6c5541ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#Man_Process_01'])[1]/preceding::th[3]</value>
      <webElementGuid>92c5195e-89eb-4599-a23d-e15baa8b53a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//thead/tr/th[2]</value>
      <webElementGuid>6a6516d2-4c70-4e1a-90f4-df3fdbbb40f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Work Type' or . = 'Work Type')]</value>
      <webElementGuid>e6840921-16a8-45b2-af01-8bc4d76bd3ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
