<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Soumya Admin Account_arrow-top</name>
   <tag></tag>
   <elementGuidId>64f37013-5029-444c-899f-246dda4561dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='arrow-top']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#arrow-top</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#arrow-top</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1274b667-2280-4032-ad75-10438fefffeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arrow-div arrow-top-pms</value>
      <webElementGuid>7b859227-761b-45d2-9783-ef5b607824b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>arrow-top</value>
      <webElementGuid>ff6989eb-0900-4afe-ae1d-8e04ed9b8040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;arrow-top&quot;)</value>
      <webElementGuid>f51e8a8d-e97c-4276-93b6-8e19a6dc4561</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='arrow-top']</value>
      <webElementGuid>a7842360-5045-4fbc-9a54-519122dc83ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swipe-area']/div</value>
      <webElementGuid>1d335266-311e-4398-a01e-596636ff06db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soumya Admin Account'])[1]/following::div[15]</value>
      <webElementGuid>9863d059-274a-4ef8-bad2-a3b2c6fc4800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User:'])[1]/following::div[15]</value>
      <webElementGuid>e86a2e4a-0011-4164-9953-2e7bd9225d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIDEBAR MENU'])[1]/preceding::div[1]</value>
      <webElementGuid>d5f301c8-cea0-4d3f-aa45-5fcfabbdf9d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WORK OUTPUT'])[2]/preceding::div[5]</value>
      <webElementGuid>ebf5f604-a36f-449c-a494-d34a3af2878c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div/div</value>
      <webElementGuid>7221f238-e859-4193-8d72-85c9d7bbdd91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'arrow-top']</value>
      <webElementGuid>ae5cfc7b-803a-4774-8123-ce8471d75259</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
