<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Work Type Definition</name>
   <tag></tag>
   <elementGuidId>65cd1c06-fe8b-464e-97e5-db81ef839c61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='level2_291']/li[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#level2_291 > li:nth-of-type(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Work Type Definition&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>9bf11c49-1ed0-4c83-801a-1a3a745970a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnMenuClick</value>
      <webElementGuid>852d5184-8ddd-4c70-ac21-20b41757d752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menuid</name>
      <type>Main</type>
      <value>251</value>
      <webElementGuid>36f159cf-873f-4b77-a662-1c0faaec50c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-path</name>
      <type>Main</type>
      <value>/phworkoutput/WorkTypeSummary.htm?menuItemId=251&amp;menuClick=true</value>
      <webElementGuid>38f72f2c-8c55-4a49-87c8-7cdb66258f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isajaxsidemenu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b057f0ef-d911-49ad-98e3-e65a1dc5a085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Work Type Definition</value>
      <webElementGuid>072bdc67-e084-4ecf-8f83-0877971da63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;level2_291&quot;)/li[@class=&quot;&quot;]</value>
      <webElementGuid>eef38d71-5f95-4200-9e77-66e6c1bd6425</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='level2_291']/li[4]</value>
      <webElementGuid>f63a3640-37a8-4012-8dcc-247cb7a48efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Type Attributes'])[1]/following::li[1]</value>
      <webElementGuid>efc70e37-a191-424e-8199-91bcc73873f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Type Category'])[1]/following::li[2]</value>
      <webElementGuid>8927d120-67d9-4e23-8f84-ae0536357ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Output Normalization'])[1]/preceding::li[1]</value>
      <webElementGuid>2415ab5b-da80-463a-ac17-2ede87eef104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Collection'])[1]/preceding::li[2]</value>
      <webElementGuid>5014e73f-dd53-4121-9c02-51fcfb8a8ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Work Type Definition']/parent::*</value>
      <webElementGuid>3965d884-fa92-468b-b205-acbb19f8e9d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[4]</value>
      <webElementGuid>29bf2357-1118-49bc-8ad1-db78fa9f79c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Work Type Definition' or . = 'Work Type Definition')]</value>
      <webElementGuid>90e3933c-4e38-4d21-8df2-dd54d97ead2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
