<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_WORK OUTPUT</name>
   <tag></tag>
   <elementGuidId>69c0b467-bc9a-4105-bc2f-6c2566fd6677</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#workOutIPAD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='workOutIPAD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;WORK OUTPUT&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a2ba93d2-984f-450b-be49-4e37cb31b198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle padding-Left-10px cursor-pointer</value>
      <webElementGuid>07bb9e8d-9cf0-46cd-93f4-d08aecd7b9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workOutIPAD</value>
      <webElementGuid>73c6a7ba-1628-4090-bbc0-823b53213c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>dbb61cfa-28c0-49b9-a3c5-b61fd7d6d838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
											WORK OUTPUT
										</value>
      <webElementGuid>aa545019-cca5-4358-b7aa-d6de3b7b9da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workOutIPAD&quot;)</value>
      <webElementGuid>d0844521-c77a-4a0e-9ec0-c63d2eff4c65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='workOutIPAD']</value>
      <webElementGuid>0aeca646-1a09-4161-a73f-247c3e5a2565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='leftMenus']/li[2]/a</value>
      <webElementGuid>eab106d3-cfd7-486b-8e72-0716d0238b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'WORK OUTPUT')]</value>
      <webElementGuid>090f97ec-515d-4777-b0ca-273bef825ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CUSTOM REPORTS'])[1]/following::a[1]</value>
      <webElementGuid>ccf4e046-217b-4b38-b681-4788a51a3eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TIMESHEET'])[1]/following::a[2]</value>
      <webElementGuid>78b1016b-7a91-481a-b381-acc4f868b86d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASSET OPTIMIZATION'])[1]/preceding::a[1]</value>
      <webElementGuid>2c1f5efe-c56b-4e8b-ba4f-a4a532013ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROJECTS'])[1]/preceding::a[2]</value>
      <webElementGuid>c8d24d75-6a58-45f6-aa11-ffb0aa33d4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WORK OUTPUT']/parent::*</value>
      <webElementGuid>30c8e121-95f4-4e10-8d9a-dc14d84c1b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>12e39f8c-2c62-49f6-a40a-ff2f3c90d228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'workOutIPAD' and (text() = '
											WORK OUTPUT
										' or . = '
											WORK OUTPUT
										')]</value>
      <webElementGuid>5d5cf5b7-2d31-4646-997b-7083a79ca402</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
