<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Work Output Settings_contentFrame</name>
   <tag></tag>
   <elementGuidId>4739af6e-23fe-4ac6-98d9-0794b6cb5f01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='contentFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#contentFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;contentFrame&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>508c8057-ddad-431a-8158-23318d60a2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ph-wo-min-height-475px</value>
      <webElementGuid>b2179860-7252-4112-88ed-f414753bd4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contentFrame</value>
      <webElementGuid>bbc01b0d-3786-4ea1-b169-86f2816850fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contentFrame</value>
      <webElementGuid>a8d398e6-5ebe-4bcc-9791-92879973029d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0fb23fbb-4449-4186-9d85-6b311bcde22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/phworkoutput/WOMetricSummary.htm?menuItemId=265&amp;menuClick=true</value>
      <webElementGuid>6cc91571-5cfa-45c0-80f3-380685b03191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentFrame&quot;)</value>
      <webElementGuid>ff9a7eeb-ba76-485b-bed9-5f95df65cfe8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='contentFrame']</value>
      <webElementGuid>f0d7559a-598d-4792-a26e-e649e8e76056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyContent']/div[3]/div/iframe</value>
      <webElementGuid>f5535468-2847-4924-b382-2a123da10b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>0e48082f-2d78-4b7a-b9b2-f0b88d5b2803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'contentFrame' and @name = 'contentFrame' and @src = '/phworkoutput/WOMetricSummary.htm?menuItemId=265&amp;menuClick=true']</value>
      <webElementGuid>60c2ee28-3048-4085-961a-8d202883f6bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
