<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_BACK</name>
   <tag></tag>
   <elementGuidId>5849e4ee-6fb8-4f33-a6c4-7f85b9c6c435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='WOMetricForm']/div[2]/div/div[2]/ol/li/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.add-new-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;BACK&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>26b33dff-dfd4-4b02-a0c8-6cfab6dbafc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add-new-name</value>
      <webElementGuid>e16c81f5-24fc-4e7a-8db1-7e01e762c89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnBackToWOMetricSummary</value>
      <webElementGuid>bf5b091e-28c6-4bd9-b0af-b43dfa9a888a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BACK</value>
      <webElementGuid>b8dbd405-1607-48c8-9d48-89c0417596cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WOMetricForm&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row navigation-area&quot;]/div[@class=&quot;col-lg-4 col-md-4 col-sm-4&quot;]/ol[@class=&quot;pull-right&quot;]/li[1]/label[@class=&quot;add-new-name&quot;]</value>
      <webElementGuid>76497d68-0c21-4e12-8289-59fd0f0e7344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Normalization Screen/Page_ProHance Work Output/Page_ProHance Work Output/iframe_Work Output Settings_contentFrame</value>
      <webElementGuid>fe1d3e45-20d4-4b81-a16f-e9b8eea2bbbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='WOMetricForm']/div[2]/div/div[2]/ol/li/label</value>
      <webElementGuid>30fd4f05-c97d-4b0c-a9c2-ec03c6ca52ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Output Normalization Details'])[1]/following::label[1]</value>
      <webElementGuid>cd64549e-e756-4e6c-868a-73481251120f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::label[1]</value>
      <webElementGuid>5d5d238b-6697-4104-81ac-19a5c85512b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BACK']/parent::*</value>
      <webElementGuid>2777767c-f139-4cb5-b635-a16bc7e040d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>92877b48-b13e-4f79-9ef9-958b0fe9569d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'BACK' or . = 'BACK')]</value>
      <webElementGuid>acf0e08d-c63a-4852-be2e-6776d2bdfa63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
