<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_WORK OUTPUT</name>
   <tag></tag>
   <elementGuidId>20544f4d-9091-4608-ab46-ca21244088d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#workOutIPAD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='workOutIPAD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;WORK OUTPUT&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e0ff559d-daa6-4e8e-b4fd-1262f7c94553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle padding-Left-10px cursor-pointer</value>
      <webElementGuid>4df47619-60e3-4ee1-b7b5-36c76bf15fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workOutIPAD</value>
      <webElementGuid>fe3b9922-dbab-48b8-821a-3ebbf8f50536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>bb5b16f9-efe3-42bf-99bb-868dc91e7460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
											WORK OUTPUT
										</value>
      <webElementGuid>f3853de6-96d6-49e6-9901-64b306b44815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workOutIPAD&quot;)</value>
      <webElementGuid>d8b591be-cf07-4c61-b465-5eb2b6199122</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='workOutIPAD']</value>
      <webElementGuid>15d0e730-cac7-4ddc-b90b-3abbf7202041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='leftMenus']/li[2]/a</value>
      <webElementGuid>025a38e5-eb29-46cd-a38e-3ca9a775a0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'WORK OUTPUT')]</value>
      <webElementGuid>5ddb2881-7c94-47ae-a5ab-a8db671c74d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CUSTOM REPORTS'])[1]/following::a[1]</value>
      <webElementGuid>4f270a8d-0c29-43f2-973b-a0f0653f93c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TIMESHEET'])[1]/following::a[2]</value>
      <webElementGuid>365412c4-eeb5-4d8e-81a8-0661bf169505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASSET OPTIMIZATION'])[1]/preceding::a[1]</value>
      <webElementGuid>32de9a6a-105e-4666-8b1b-5197b7161f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROJECTS'])[1]/preceding::a[2]</value>
      <webElementGuid>396ba43b-bef8-4593-913c-8696e8068a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WORK OUTPUT']/parent::*</value>
      <webElementGuid>16482d2b-4361-4ce8-8992-a4c5f1eb9fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>e82ab342-a8a1-451e-b7aa-5d77247d8c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'workOutIPAD' and (text() = '
											WORK OUTPUT
										' or . = '
											WORK OUTPUT
										')]</value>
      <webElementGuid>a81fdafe-65a1-4d01-b27e-0d3d59bf67db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
