<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Soumya Admin Account_arrow-top</name>
   <tag></tag>
   <elementGuidId>895b125a-d835-4817-97b8-aa3e0e84e8fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#arrow-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='swipe-area']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#arrow-top</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e6ff8a93-04d1-486b-a627-f64ef964cd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arrow-div arrow-top-pms</value>
      <webElementGuid>681067d5-ff22-4333-851c-64f1286d01ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>arrow-top</value>
      <webElementGuid>db48bc13-d1e7-4b08-84b0-43636aec5bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;arrow-top&quot;)</value>
      <webElementGuid>e04dd862-28f6-4302-8536-630c8b0bf506</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='arrow-top']</value>
      <webElementGuid>88c631d0-d789-42e2-8a99-b228057120c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swipe-area']/div</value>
      <webElementGuid>e4f23e9f-2768-4788-8bb1-52713f1710ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soumya Admin Account'])[1]/following::div[15]</value>
      <webElementGuid>69a8eb44-be89-49ac-9384-c94fe94b9f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User:'])[1]/following::div[15]</value>
      <webElementGuid>02c638de-4ce6-48fb-9a3f-011168f300da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIDEBAR MENU'])[1]/preceding::div[1]</value>
      <webElementGuid>6ee8458f-c9e3-436c-a73f-6acb43b2393b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WORK OUTPUT'])[2]/preceding::div[5]</value>
      <webElementGuid>1fc04285-a91f-4ac1-bcdc-99e933a8666b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div/div</value>
      <webElementGuid>015d671f-f3ea-4215-be67-79f61f753ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'arrow-top']</value>
      <webElementGuid>62ce1e33-4e76-46aa-a83a-592fe9d1e852</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
