<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modify_icon</name>
   <tag></tag>
   <elementGuidId>d458cbc7-9d0e-4afc-920d-8d2989da562c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table/tbody/tr/td[1]/a/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
