<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Soumya Admin Account_arrow-top</name>
   <tag></tag>
   <elementGuidId>256fb280-4a4d-43ab-af78-e4c4e71a1d20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#arrow-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='swipe-area']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#arrow-top</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c1b2da1a-cdb0-46b5-afd5-3cd0d4f220f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arrow-div arrow-top-pms</value>
      <webElementGuid>5b97605e-ee21-4829-90ba-155a157cc183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>arrow-top</value>
      <webElementGuid>78bf0328-2199-48a4-8382-45b9d6dbe4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;arrow-top&quot;)</value>
      <webElementGuid>c55b0b19-9930-48e5-8fad-6909e33eac11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='arrow-top']</value>
      <webElementGuid>1a1980a1-1711-4a91-8eef-bfaa7d79fdf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swipe-area']/div</value>
      <webElementGuid>f51c2a0f-351a-49ec-85fd-661ad1e8606c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soumya Admin Account'])[1]/following::div[15]</value>
      <webElementGuid>e97f5bb4-9e62-4ce3-b670-64aaf5e87ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User:'])[1]/following::div[15]</value>
      <webElementGuid>559888ee-a7f6-464e-80f2-bcd9b0b79d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIDEBAR MENU'])[1]/preceding::div[1]</value>
      <webElementGuid>8b091301-0b8e-435e-8fbb-f7a5de77f45b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WORK OUTPUT'])[2]/preceding::div[5]</value>
      <webElementGuid>801da8ab-86f9-4f29-8d76-ae66145604b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div/div</value>
      <webElementGuid>95c9f3ca-931c-43eb-a15b-827e425f3403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'arrow-top']</value>
      <webElementGuid>e59c378f-5951-4500-8203-5af5b29eb426</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
