<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Output Dashboard</name>
   <tag></tag>
   <elementGuidId>c96bae2e-5b65-4bf7-adf0-46b44edbfcd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.nav-side-menu-selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='level2_162']/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Output Dashboard&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>efa306b6-908b-4773-b6b9-ab2da04241b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-side-menu-selected </value>
      <webElementGuid>9f1327be-e4d3-45da-9a53-5caf05848789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnMenuClick</value>
      <webElementGuid>8ab385ee-61fd-400f-af7b-8281a8099d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menuid</name>
      <type>Main</type>
      <value>123</value>
      <webElementGuid>dc632701-50e2-44c5-b72c-35bbb2b8efc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-path</name>
      <type>Main</type>
      <value>/phworkoutput/NWorkoutputDashboard.htm?menuItemId=123&amp;menuClick=true</value>
      <webElementGuid>bc48e180-fec1-48c3-b427-d4301753e1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isajaxsidemenu</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7a22ea94-70bf-4d8a-a66b-ae5b08029e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Output Dashboard</value>
      <webElementGuid>f250ba1f-2d6d-4fa4-b702-7e273b769b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;level2_162&quot;)/li[@class=&quot;nav-side-menu-selected&quot;]</value>
      <webElementGuid>e1475d47-39ac-4758-9d59-0ec125a959c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='level2_162']/li</value>
      <webElementGuid>df10724c-2e16-4b9d-9e07-6a8e0659b42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Output Analytics'])[1]/following::li[1]</value>
      <webElementGuid>15b5a0b6-356f-4b8e-9f37-cd8537370ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WORK OUTPUT'])[2]/following::li[2]</value>
      <webElementGuid>f9ff23bd-c1fc-480a-a341-bf8a7a963092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Output Scorecard'])[1]/preceding::li[1]</value>
      <webElementGuid>84c3934e-d141-4349-a7b2-a806398a0516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprehensive Output Analytics'])[1]/preceding::li[2]</value>
      <webElementGuid>45f598fd-1ee6-406d-a266-c47aab1ed389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Output Dashboard']/parent::*</value>
      <webElementGuid>62a6ea4f-e4cf-4b95-95a7-448c821de537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li</value>
      <webElementGuid>0d8f616a-15d7-4182-a301-6b9bcb8bd788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Output Dashboard' or . = 'Output Dashboard')]</value>
      <webElementGuid>9010f7fc-2d88-4de9-bbd7-1edaf10ffb43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
