<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add New Widget</name>
   <tag></tag>
   <elementGuidId>53db4587-f893-48cb-b74a-5e7d06d883ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#show-content-menu-main</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='show-content-menu-main']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#show-content-menu-main</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3caf27c1-7196-4408-8e0b-01cabd5b1ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add-new-name</value>
      <webElementGuid>5f52bff9-fd11-4d76-a4dc-7b3fdb52f0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show-content-menu-main</value>
      <webElementGuid>f0de7316-d81d-42b7-9861-3c2982cc4422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add New Widget</value>
      <webElementGuid>c7905094-4199-496a-88f9-947c80dfedc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show-content-menu-main&quot;)</value>
      <webElementGuid>27aa0ecf-600b-41b7-a1f9-b3f3714962e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='show-content-menu-main']</value>
      <webElementGuid>7a752763-e4e7-4136-a0e3-1f2ace6e95d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show-content-menu']/div/span</value>
      <webElementGuid>c662d5ef-cc0d-4c22-9fc0-39f731ed198c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Output Data Management.'])[1]/following::span[1]</value>
      <webElementGuid>65ab4819-72af-4cfa-b0ba-ea7dce62e7b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Import'])[2]/following::span[1]</value>
      <webElementGuid>5d0666de-0328-4207-a0e0-4d6f6b04a646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/div/div/div/div/span</value>
      <webElementGuid>e2f19fa2-398d-4ac3-9233-d95a1b3ebbbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'show-content-menu-main' and (text() = ' Add New Widget' or . = ' Add New Widget')]</value>
      <webElementGuid>b5b01209-a950-4027-a245-25fedfe28463</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
