<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Work Type Category</name>
   <tag></tag>
   <elementGuidId>3439deed-7533-40a2-ad0f-baf90fdd3e3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#level2_291 > li:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='level2_291']/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Work Type Category&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5991d38a-8e4b-489d-a97a-36d01887a1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnMenuClick</value>
      <webElementGuid>424eafa1-7522-4d2e-a1a4-feb34d279a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menuid</name>
      <type>Main</type>
      <value>302</value>
      <webElementGuid>258984ea-f8fd-4c50-886f-fab9cd101615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-path</name>
      <type>Main</type>
      <value>/phworkoutput/WorkOutputCategorySummary.htm?menuItemId=302&amp;menuClick=true</value>
      <webElementGuid>8fbeeaf5-7e96-4135-b8d3-32523dadefaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isajaxsidemenu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>18ff6706-d4f0-4366-b8b1-0fbbd905898d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Work Type Category</value>
      <webElementGuid>62958f13-0870-4bb3-a1c6-84e7a863a2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;level2_291&quot;)/li[@class=&quot;&quot;]</value>
      <webElementGuid>2a2168be-02af-491c-bed3-1f403fe4a51a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='level2_291']/li[2]</value>
      <webElementGuid>65f00130-9293-4809-a873-ae0496b8f67b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Output Parameter'])[1]/following::li[1]</value>
      <webElementGuid>df7d2f22-fe1f-4fdd-aff8-2fc92dbfd8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration'])[1]/following::li[2]</value>
      <webElementGuid>7739ac3d-882e-451e-bfe5-1af74f57630c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Type Attributes'])[1]/preceding::li[1]</value>
      <webElementGuid>a9506170-136c-4995-9e0e-1f97e30d589f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Type Definition'])[1]/preceding::li[2]</value>
      <webElementGuid>e0e7eaa4-398a-4029-8206-131f451553cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Work Type Category']/parent::*</value>
      <webElementGuid>f252976c-57f1-4168-9e13-735622da8d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[2]</value>
      <webElementGuid>1fdda462-3f0f-4135-8645-d8f525b6898a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Work Type Category' or . = 'Work Type Category')]</value>
      <webElementGuid>10a6cfc5-f07c-40e5-9045-4296cfb9c8be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
